version: "3.8"

services:

    db:
        image: postgres
        container_name: local_pgdb
        restart: always
        environment:
            POSTGRES_USER: 'sojue'
            POSTGRES_PASSWORD: 'sojue3141592'
        ports:
            - '5430:5432'

    grafana:
        image: grafana/grafana-enterprise
        container_name: grafana
        restart: always
        environment:
            GF_SECURITY_ADMIN_USER: 'sojue'
            GF_SECURITY_ADMIN_PASSWORD: 'sojue3141592'
        ports:
            - '3025:3000'


